テーブル作成中、提出用
posse-ap/gen1.5-taiki455 pull request #12
Opened 2022-01-08 09:58 UTC by taiki455

・テーブルを作成したい（時間管理＋合計時間算出＋グラフ反映）

2022-01-12 11:41 UTC, Mitsuru53 requested changes
数点コメントいたしました!

あと、vscodeのプラグインでテーブル情報などを視覚的にみるツールを利用されていると思いますが、そちらと、sqlの内容が一致していることを確認できるようなスクショなどをいただけると幸いです
webapmakes/test.vuerd.json

2022-01-12 11:41 UTC, Mitsuru53 commented on webapmakes/mysql/sql/init.sql
>    `id` INT NOT NULL PRIMARY KEY,
idにauto incrementを設定して欲しいです
https://dev.mysql.com/doc/refman/8.0/ja/example-auto-increment.html

2022-01-12 11:41 UTC, Mitsuru53 commented on webapmakes/mysql/sql/init.sql
> +  `language_id` INT NOT NULL COMMENT 'study_languageのidカラムの外部キー',
外部キー制約をつけてください
これにより、contentsテーブルに存在しないidが挿入されないようになります

またon deleteオプションも合わせてつけてください(これが何かは調べてください)
https://dev.mysql.com/doc/refman/5.6/ja/create-table-foreign-keys.html

2022-01-12 11:41 UTC, Mitsuru53 commented on webapmakes/mysql/sql/init.sql
> +  `content_id` INT NOT NULL COMMENT 'study_contentsのidカラムの外部キー'
ditto

2022-01-12 11:41 UTC, Mitsuru53 commented on webapmakes/mysql/sql/init.sql
> +  `id` INT NOT NULL PRIMARY KEY,
idにauto incrementを設定して欲しいです
https://dev.mysql.com/doc/refman/8.0/ja/example-auto-increment.html

2022-01-12 11:41 UTC, Mitsuru53 commented on webapmakes/mysql/sql/init.sql
> +  `graph_color` VARCHAR(20) COMMENT '学習言語ごとのグラフの色'
[ask]ここはnot null要らないですか？

2022-01-12 11:41 UTC, Mitsuru53 commented on webapmakes/mysql/sql/init.sql
> +  `graph_color` VARCHAR(20) COMMENT '学習言語ごとのグラフの色'
ditto

2022-01-12 11:46 UTC, taiki455 commented
> 数点コメントいたしました!
> 
> あと、vscodeのプラグインでテーブル情報などを視覚的にみるツールを利用されていると思いますが、そちらと、sqlの内容が一致していることを確認できるようなスクショなどをいただけると幸いです webapmakes/test.vuerd.json
<img width="1250" alt="スクリーンショット 2022-01-12 20 46 19" src="https://user-images.githubusercontent.com/74663828/149134700-b9cdfac5-6b2a-475f-b986-068d03c67595.png">

2022-01-12 12:04 UTC, taiki455 commented on webapmakes/mysql/sql/init.sql
>    `id` INT NOT NULL PRIMARY KEY,
<img width="484" alt="スクリーンショット 2022-01-12 21 01 58" src="https://user-images.githubusercontent.com/74663828/149137065-625249b4-8b22-4c4d-9881-0bbc264b7a5c.png">

2022-01-12 12:10 UTC, taiki455 commented on webapmakes/mysql/sql/init.sql
> +  `id` INT NOT NULL PRIMARY KEY,
https://github.com/posse-ap/gen1.5-taiki455/pull/12/commits/f6e1ec33bf3669fd36d05b9adacce83907233b60

2022-01-24 05:53 UTC, merged

2022-02-08 10:47 UTC, taiki455 commented on webapmakes/mysql/sql/init.sql
>    `id` INT NOT NULL PRIMARY KEY,
<img width="858" alt="スクリーンショット 2022-02-08 19 47 02" src="https://user-images.githubusercontent.com/74663828/152972152-f0fc5677-c415-4698-addb-80e9e0918ad3.png">
設定しました。

2022-02-08 10:49 UTC, taiki455 commented on webapmakes/mysql/sql/init.sql
> +  `graph_color` VARCHAR(20) COMMENT '学習言語ごとのグラフの色'
<img width="858" alt="スクリーンショット 2022-02-08 19 47 02" src="https://user-images.githubusercontent.com/74663828/152972297-4f5f3caa-1e64-48aa-9ba8-af319a9b0fb7.png">
not nullが抜け落ちていたので 追加しました。

2022-02-08 10:49 UTC, taiki455 commented on webapmakes/mysql/sql/init.sql
> +  `id` INT NOT NULL PRIMARY KEY,
<img width="858" alt="スクリーンショット 2022-02-08 19 47 02" src="https://user-images.githubusercontent.com/74663828/152972464-078f3143-a783-499d-ab0b-1984f5e5a914.png"
設定しました。

2022-02-08 10:50 UTC, taiki455 commented on webapmakes/mysql/sql/init.sql
> +  `id` INT NOT NULL PRIMARY KEY,
設定しました
<img width="858" alt="スクリーンショット 2022-02-08 19 47 02" src="https://user-images.githubusercontent.com/74663828/152972559-11299012-7cba-4d14-a62c-160c4e92b29d.png">
。

2022-02-08 11:39 UTC, taiki455 commented on webapmakes/mysql/sql/init.sql
> +  `language_id` INT NOT NULL COMMENT 'study_languageのidカラムの外部キー',
<img width="858" alt="スクリーンショット 2022-02-08 20 38 29" src="https://user-images.githubusercontent.com/74663828/152979794-ff3d84ab-4a91-4052-b6ff-8091425f6076.png">
外部キー制約+on delete設定しました